name: 🚀 Deploy SSH
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Atualizando VPS
        uses: appleboy/ssh-action@master
        with:
          host: 89.117.79.191
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            TARGET="wandeath.com"
            echo "📂 Entrando na pasta /var/www/$TARGET..."
            cd /var/www/$TARGET
            
            echo "⚙️ Configurando diretório seguro..."
            git config --global --add safe.directory /var/www/$TARGET
            
            echo "📥 Buscando atualizações do GitHub..."
            git fetch origin main
            
            echo "🧹 Resetando para a versão mais recente..."
            git reset --hard origin/main
            
            echo "🔑 Ajustando permissões..."
            chown -R deployer:www-data /var/www/$TARGET
            chmod -R 775 /var/www/$TARGET
            
            echo "🌐 Recarregando Nginx..."
            systemctl reload nginx
            
            echo "✅ DEPLOY FINALIZADO COM SUCESSO!"
